# config file for automatic testing at travis-ci.org
language: python

python:
    - "3.4"

install:
    # install test dependencies
    - pip install -r requirements-dev.txt

    # install your own package + executables
    - pip install --editable .

script:
    # command to run tests and collect test coverage
    - inv test

notifications:
    email: true

after_success:
    codecov
